name: advance
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: 3.32.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  intl: ^0.20.2
  file_selector: ^1.0.3
  http: ^1.3.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/acev.png
